### ISSUE TITLE
Evitar submit no enter

### ISSUE THREAD

**Issue by douglaswp** [valdeirs2/woocommerce-shipping-calculator-in-product#1]
> Estou criando essa issue pra depois fazer um PR

Hoje quando digitamos um CEP e acionamos o cálculo com ENTER o site tenta enviar o produto ao carrinho de compras. O ideal seria acionar o calculo de frete tanto n enter quanto no clique.

**Comment by luizbills** [comment]
> Hoje quando digitamos um CEP e acionamos o cálculo com ENTER o site tenta enviar o produto ao carrinho de compras.

Enviar apertando enter é uma opção muito importante, não deveria ser retirado. O que provavelmente está acontecendo é que os campos da calculadoras devem estar sendo incluídos dentro do `form` do produto. Colocando fora do `form` do produto já resolve a situação.

**Comment by douglaswp** [comment]
Exatamente @luizbills 
Mas vou retirar somente o submit do form do produto, e não do cálculo.
Mais tarde já envio o PR com a alteração

**Comment by valdeirs2** [comment]
@douglaswp, obrigado pelo feedback. O problema foi resolvido aqui:

https://github.com/valdeirs2/woocommerce-shipping-calculator-in-product/commit/70d0b9047f9f98849167b87efab64817e31eef9b

Vou fechar a Issue por hora.

abs
