### ISSUE TITLE
Cálculo baseado em áreas de entrega não funciona

### ISSUE THREAD

**Issue by callmeteus** [valdeirs2/woocommerce-shipping-calculator-in-product#11]
No formato atual do plugin, o cálculo baseado em áreas de entrega do Woocommerce não funciona, pois a função `load_shipping_methods` precisa do parâmetro `state` preenchido corretamente, o que na maioria das vezes não vai estar.

Eu fiz uma rápida correção para isto usando a API do ViaCEP, e essa correção se encaixa somente para CEPs brasileiros, segue a modificação feita no arquivo ajax-postcode.class.php:

```
// Check if customer has a shipping country
if (WC()->customer->get_shipping_country()) {
	// Startup the destination data
	$destination 						= [
		"country" 						=> WC()->customer->get_shipping_country(),
		"postcode" 						=> sanitize_text_field($request["postcode"])
	];

	// Check if it's a brazilian postcode (nnnnn-nnn, without the "-" we have 8 total digits)
	if (strlen(str_replace("-", "", $request["postcode"])) === 8) {
		try {
    		// Get brazilian postcode data
    		$CEPData 					= json_decode(file_get_contents("https://viacep.com.br/ws/" . $request["postcode"] . "/json/"));

    		// Merge the data
    		$destination["state"] 		= $CEPData->uf;
    		$destination["city"] 		= $CEPData->localidade;
    		$destination["address"] 	= $CEPData->logradouro;
    		$destination["address_2"] 	= $CEPData->complemento;
    	} catch(Exception $e) {
    		// If any error happened, we cancel the search
    		return false;
    	}
	}
} else {
	// Get the default customer location
    $destination 						= wc_get_customer_default_location();
}
```

Eu ia abrir um pull request, mas dei uma reidentada no plugin, então o arquivo vai estar um pouco diferente, prefiro publicar aqui somente a solução direta.

**Comment by callmeteus** [comment]
Acredito também que esse possa ter sido o problema do outro bug report aberto.
Acredito que o usuário tinha alguma área de entrega, e o mesmo não estava sendo exibido devido ao campo em branco.

**Comment by valdeirs2** [comment]
Olá, @theprometeus 

Obrigado pelo seu report!

Os casos em que o cálculo não funcionava por falta de dados no parâmetro state acontece porque a opção de "Localização padrão do cliente" nas configurações do WooCommerce está marcada como "Nenhuma localização". 

Para contornar isto, estou alterando esta opção quando nenhuma localização é selecionada.

Como vc pode ver aqui: https://github.com/valdeirs2/woocommerce-shipping-calculator-in-product/commit/2adbb7f29b4ce8eb61bb6d26e11675a8c91662bc
