### ISSUE TITLE
Erro no woocommerce 3.7

### ISSUE THREAD

**Issue by willkoga** [valdeirs2/woocommerce-shipping-calculator-in-product#12]
Alguém ai com bugs no woocommerce 3.7, estou usando com o WooCommerce Correios 3.7.2 e ele tem alguns erros esquisitos quem sabe alguém pode me ajudar:

1 - o método de envio não aparece se a opção "Exibir estimativa de entrega" estiver selecionada. Após remover a opção, é preciso deletar o método e criar um novo pra ele aparecer nas opções novamente.

2 - as opções na aba Calculadora de Frete na Página do Produto não refletem no plugin, posso deselecionar o uso do plugin nas opções, ao atualizar voltam todas no default do woo-settings.class.php e alterar os defaults por lá também não reflete no funcionamento do plugin.

**Comment by valdeirs2** [comment]
Olá, @willkoga.

Obrigado pelo seu report.

Não consegui simular o seu primeiro erro. Fiz diversos testes em cima da versão 3.7 e não obtive este erro. Imagino que outro plugin ou o seu tema está conflitando com o meu.

Já o segundo erro foi corrigido aqui https://github.com/valdeirs2/woocommerce-shipping-calculator-in-product/commit/076ea6ddebd84e4b99adced03a1f70a4833342cd


Obrigado
