### ISSUE TITLE
Não salva mais as configurações

### ISSUE THREAD

**Issue by webalvk** [valdeirs2/woocommerce-shipping-calculator-in-product#13]
Olá,

Notei hoje... que o plugin, apesar de continuar funcionando... não esta mais salvando as configurações.

Testei em dois sites diferentes.. que eu já utilizava o plugin anteriormente... 

Existe a possibilidade de ser lançada alguma atualização para corrigir?

Att,
Priscila

**Comment by valdeirs2** [comment]
Olá Priscila.

Obrigado pelo report!

Resolvido [aqui](https://github.com/valdeirs2/woocommerce-shipping-calculator-in-product/commit/076ea6ddebd84e4b99adced03a1f70a4833342cd)


Abs
