### ISSUE TITLE
Adicionar video explicativo para configuração no README.md e melhorar descrição

### ISSUE THREAD

**Issue by leonardola** [valdeirs2/woocommerce-shipping-calculator-in-product#15]
Se você assim como eu não entendeu a explicação que está no readme. Siga os passos abaixo:

encontrei este video que explica melhor como configurar o plugin https://www.youtube.com/watch?v=Bf91UeNa7Eg&feature=emb_logo

Estando no admin vá ao menu Woocommerce > Configurações
depois vá a aba produtos
depois clique no link Calculadora de Frete na Página do Produtos

**Comment by RafaelAngelo1999** [comment]
aqui eu nao consigo clicar na calculadora, esta tranquilo para voces o plugin ?

**Comment by valdeirs2** [comment]
Obrigado pela informação do vídeo.
Como não é um problema no plugin, estou fechando a issue.
