### ISSUE TITLE
Problema de simulação de frete da página do produto.

### ISSUE THREAD

**Issue by Gilbert-Marcone** [valdeirs2/woocommerce-shipping-calculator-in-product#16]
Olá! Tudo bem?

 Estou enfrentando problemas em relação ao plugin woocommerce-shipping-calculator-in-product quando vou simular o frete na página do produto no celular. 

Tendo em vista que utilizo o plugin do Claudio Sanches - Correios for WooCommerce, que configurei as áreas de entrega e peso e dimensões do produto. Ao simular o frete no Desktop, a simulação de frete aparece normalmente na página do produto.
Ao fazer o mesmo em um celular, aparece uma mensagem de erro informando: '' nenhuma forma de entrega disponível''. 

O que poderia ser?

OBS: Testei o plugin do  Claudio Sanches - Correios for WooCommerce com outro plugin de calculadora na página do produto e a simulação tanto no descktop quando no mobile deu certo. No entanto quero utiliza o woocommerce-shipping-calculator-in-product pelo possibilidade de personalização.

**Comment by lucastaglia** [comment]
Mesmo problema por aqui. Conseguiu resolver @Gilbert-Marcone?

**Comment by valdeirs2** [comment]
@Gilbert-Marcone e @lucastaglia 

Por favor, forneçam mais detalhes, como seu tema por exemplo.
Se possível, compartilhem o link do site para que eu possa avaliar.
