### ISSUE TITLE
Possível problema com frete grátis e regiões

### ISSUE THREAD

**Issue by baitasite** [valdeirs2/woocommerce-shipping-calculator-in-product#17]
Fala meus queridos! Percebi que ao utilizar duas regiões (pode ser que com apenas uma também aconteça), o frete grátis ativa para regiões que não tem o método ativo.

Ex: ativei o método frete grátis apenas para SP e SC, porém quando vou calcular na página do produto, se eu coloco um CEP De MG, ele mostra Frete Grátis, mas lá no checkout ele cobra...

**Comment by baitasite** [comment]
Detalhes adicional que acabei de perceber, ela não está calculando o valor declarado, apenas valor sem declarar.

**Comment by atorresbr** [comment]
> Fala meus queridos! Percebi que ao utilizar duas regiões (pode ser que com apenas uma também aconteça), o frete grátis ativa para regiões que não tem o método ativo.
> 
> Ex: ativei o método frete grátis apenas para SP e SC, porém quando vou calcular na página do produto, se eu coloco um CEP De MG, ele mostra Frete Grátis, mas lá no checkout ele cobra...

o plugin está muito desatualizado, faz anos que nao atualizam, entao voce vai ter que trabalhar o código

**Comment by valdeirs2** [comment]
Não consegui reproduzir os problemas citados.
Se possível, compartilhe o link da loja para que eu possa verificar.

Nos diversos testes que fim aqui, o plugin se comportou conforme esperado. Para as areas de entrega, você pode cria-las usando range de cep.
