### ISSUE TITLE
Não mostra o cálculo se produto é simples

### ISSUE THREAD

**Issue by BrunoBrasolin** [valdeirs2/woocommerce-shipping-calculator-in-product#18]
Ao colocar um CEP na página de single product ele apresenta a mensagem "Por favor, escolha uma opção antes de calcular."
![image](https://user-images.githubusercontent.com/50347981/123437267-ded8c380-d5a5-11eb-879e-894148226ddd.png)

[Link para testar](http://ambiente-desenvolvimento.provisorio.ws/bruno-brasolin/desafio-4/loja/tenis/tenis-nike-air-force-1-07-lv8-masculino/)

**Comment by BrunoBrasolin** [comment]
Na minha simgle-product.php não existia um `<input name="add-to-cart" />`

**Comment by Mateus1Hoffmann** [comment]
@BrunoBrasolin estou rodando a internet toda e não estou achando solução para esse mesmo problema.

Vi que vc conseguiu resolver com uma linha de código.

Eu não sou desenvolvedor e preciso de ajuda para fazer funcionar corretamente o plug-in.

Você consegue mostrar um tipo de passo como fez para resolver?

Acredito que outras pessoas tb estão procurando por essa resposta.

Obg!

**Comment by BrunoBrasolin** [comment]
Boa tarde, @Mateus1Hoffmann 

Se eu não me engano, foi apenas colocar esta linha

`<input type="hidden" name="add-to-cart" value="<?= get_the_ID() ?>">`

Creio que com isso resolva o problema.


![image](https://user-images.githubusercontent.com/50347981/154560653-a7fbda84-41d7-45bc-be15-3206c9a547b4.png)

**Comment by Mateus1Hoffmann** [comment]
> Boa tarde, @Mateus1Hoffmann
> 
> Se eu não me engano, foi apenas colocar esta linha
> 
> `<input type="hidden" name="add-to-cart" value="<?= get_the_ID() ?>">`
> 
> Creio que com isso resolva o problema.
> 
> ![image](https://user-images.githubusercontent.com/50347981/154560653-a7fbda84-41d7-45bc-be15-3206c9a547b4.png)

Cara, mto mto mto obg!

Resolveu!
