### ISSUE TITLE
compatibilidade versao mobile e erro de calculo

### ISSUE THREAD

**Issue by grupoclique** [valdeirs2/woocommerce-shipping-calculator-in-product#19]
Versão mobile fica muito desproporcional e não há como ajustar.
Outro problema é que como configurei o produto para pular a fase de adicionar ao carrinho e ir até o checkout direto ele da o erro "por favor, escolha uma opção antes de calcular."

**Comment by valdeirs2** [comment]
Em relação a versão mobile, você precisa ajustar o CSS do seu tema. Isto não é um problema do plugin, mas apenas um ajuste que você precisa fazer. Dificilmente o plugin estará 100% estilizado em todos os temas.
