### ISSUE TITLE
Mensagem de doação não sai da tela depois de fechar

### ISSUE THREAD

**Issue by Frisoni** [valdeirs2/woocommerce-shipping-calculator-in-product#2]
A mensagem de doação, mesmo depois de fechada, sempre aparece de volta, 
Seria bom não mostra-la mais ou mostrar só depois de x dias.
Also, considere usar paypal pois o plugin pode ser usado por estrangeiros também.

**Comment by valdeirs2** [comment]
Em algum PR atrás, a mensagem foi movida para uma área mais discreta.

Obrigado pelas sugestões.
