### ISSUE TITLE
Cálculo incorreto para grande quantidade de produtos.

### ISSUE THREAD

**Issue by StefanySantogo** [valdeirs2/woocommerce-shipping-calculator-in-product#20]
Estou usando os plugin woocomerce, e correios (Claudio sanches) e 
woocommerce-shipping-calculator-in-product.
O cálculo está com uma diferença de mais do que o dobro no valor de entrega, quando é incluído uma grande quantidade de produtos. São produtos para abastecer papelarias então sempre vende acima de 100 unidades e o plugin calcula separadamente a embalagem, isso leva o valor nas alturas. O que deve ser feito e configurado pra que o plugin calcule o produto somando apenas suas medidas e seu peso como é feito no site dos correios?  Bom ressaltando que em pouca quantidade o valor é calculado corretamente.

**Comment by valdeirs2** [comment]
Olá.

O plugin não cria nenhuma regra de cálculo e nem modifica as regras criadas pelo plugin do Cláudio.
Por favor, verifique se o calculo na pagina do produto está igual ao cálculo da página do carrinho.

Se possível, compartilhe o link da loja para que eu possa entender melhor.
