### ISSUE TITLE
Mensagem "Por favor, escolha uma opção antes de calcular."

### ISSUE THREAD

**Issue by kikofredboy** [valdeirs2/woocommerce-shipping-calculator-in-product#21]
Fiz a instalação normal com todas as configurações idênticas aos tutoriais que vi no youtube, porem, porem esta dando uma mensagem assim "Por favor, escolha uma opção antes de calcular.".
O problema é que não aparece opção para que eu possa selecionar.
Oque posso ter feito de errado?

**Comment by Mateus1Hoffmann** [comment]
Para quem ainda não encontrou a solução disso, fiz essa alteração e deu certo:

#18 

✌

**Comment by valdeirs2** [comment]
Obrigado pelo report.
Subi uma atualização com a solução citada pelo @Mateus1Hoffmann [7970651](https://github.com/valdeirs2/woocommerce-shipping-calculator-in-product/commit/7970651e012efb3677074b01940984075f4c52cd)
