### ISSUE TITLE
Nenhuma forma de entrega disponível.

### ISSUE THREAD

**Issue by guilherme-oliveria** [valdeirs2/woocommerce-shipping-calculator-in-product#23]
não consigo fazer funcionar, uso Wordpress versão 5.9.3
![Captura de Tela 2022-05-19 às 18 04 19](https://user-images.githubusercontent.com/22917578/169404588-d3bb3e9b-106f-419b-b3c5-5d42cc78c535.png)
![Captura de Tela 2022-05-19 às 18 12 03](https://user-images.githubusercontent.com/22917578/169405490-daafd439-3d16-4e46-a1a7-33f980ba622e.png)
.

**Comment by guilherme-oliveria** [comment]
O problema para ser o valor de 19,39, produto com preço R$35 calcula, pq isso ?

**Comment by valdeirs2** [comment]
@guilherme-oliveria. 

Veja se a opção "ativar valor declarado" está habilitada nas configurações de entrega. Caso esteja, isto é funcionamento padrão dos Correios que possui valor máximo e mínimo de entrega caso use este seguro.

**Comment by valdeirs2** [comment]
A versão Open Source do plugin foi descontinuada.
Para ter acesso a nova versão com correções, suporte e novas funcionalidades, acesse: https://solucoes-woocommerce.com.br/

**Comment by atorresbr** [comment]
> A versão Open Source do plugin foi descontinuada. Para ter acesso a nova versão com correções, suporte e novas funcionalidades, acesse: https://solucoes-woocommerce.com.br/

BOA !, a era Plugin Grátis tem que acabar. Na versão grátis o máximo que você ganha é avaliação negativa.
