### ISSUE TITLE
Erro de cálculo

### ISSUE THREAD

**Issue by Guilherme-tester** [valdeirs2/woocommerce-shipping-calculator-in-product#24]
No WordPress Versão 6.0 ele não calcula o frete dos estados. 
Sempre calcula o mesmo frete para todos os estados e não altera mais, tornando o frete fixo

**Comment by valdeirs2** [comment]
@Guilherme-tester. 

Fiz vários testes aqui e não identifiquei este problema. O plugin se comportou de maneira normal, mostrando os fretes iguais aos do carrinho. Veja se não há algum outro plugin armazenando cache da requisição ou algo do tipo

**Comment by Guilherme-tester** [comment]
No meu caso é frete estático por estado e não dinâmico, então cada estado
deve apresentar um frete diferente, e não é o que está acontecendo

Em sáb., 4 de jun. de 2022 00:08, valdeirs2 ***@***.***>
escreveu:

**Comment by valdeirs2** [comment]
A versão Open Source do plugin foi descontinuada.
Para ter acesso a nova versão com correções, suporte e novas funcionalidades, acesse: https://solucoes-woocommerce.com.br/
