### ISSUE TITLE
Seu plugin está solicitando doações insistentemente, não adianta fechar que ele sempre volta a pedir, precisa de correção.

### ISSUE THREAD

**Issue by vaucci** [valdeirs2/woocommerce-shipping-calculator-in-product#25]
Seu plugin está solicitando doações insistentemente, não adianta fechar, ele sempre volta a pedir, precisa de correção, pois tenho certeza de que tem muita gente incomodada de ter que conviver com seu pedido de doação permanenten no painel do wordpress.

![Screenshot_1](https://user-images.githubusercontent.com/57840299/184013339-aa21bd03-e21e-426e-865a-77608f63fdfa.png)

**Comment by valdeirs2** [comment]
@vaucci Tudo bem?

Esta versão open source foi descontinuada, pois necessitava de atualizações para corrigir questões de segurança, suporte a novas versões do WordPress e WooCommerce, além de ajustes no próprio calculo. Para que pudéssemos trabalhar nessas melhorias, foi necessário descontinuar esta versão e focar na versão paga, que está disponível em  http://solucoes-woocommerce.com.br/.
