### ISSUE TITLE
Não compatível com Woocommerce 3.3.3

### ISSUE THREAD

**Issue by Frisoni** [valdeirs2/woocommerce-shipping-calculator-in-product#3]
Na nova versão as opções de exibição do produto não estão mais na aba Configurações > Produto, portanto não é possível configurar o plugin. Essas configurações foram para o customizer do tema.
Testado com os temas Flatsome e Storefront.

**Comment by valdeirs2** [comment]
@Frisoni, obrigado pelo feedback. Isto foi corrigo graças a contribuição do @Dermix .

Abs
