### ISSUE TITLE
Não mostra o cálculo se produto não é simples

### ISSUE THREAD

**Issue by Frisoni** [valdeirs2/woocommerce-shipping-calculator-in-product#5]
Para um produto configurado como simples funciona.
Porém, qualquer outro tipo de produto que não seja variável aparece a mensagem: Por favor, escolha uma opção antes de calcular

**Comment by valdeirs2** [comment]
@Frisoni, não entendi muito bem. Você só está conseguindo usar o plugin quando o produto é variável?

Poderia me enviar o link do produto que está testando?

**Comment by Frisoni** [comment]
ACHO que o plugin tá funcionando só quando o tipo de produto é simples ou quando é varíavel. Para outros tipos de produtos sempre dá erro como se faltasse escolher a variação.
No meu caso uso o plugin Woo Subscription, então o produto é uma assinatura.
Exemplo de produto assinatura:
https://woocommerce-130333-449071.cloudwaysapps.com/produto/mensal-porte-p/
Mudei um produto para o tipo Grupo de Produto, e dá o mesmo erro:
https://woocommerce-130333-449071.cloudwaysapps.com/produto/mensal-porte-m/

Esse é um ambiente de testes. Se precisar de mais alguma coisa é só falar.

**Comment by valdeirs2** [comment]
@Frisoni, veja se este PR resolveu pra vc.
https://github.com/valdeirs2/woocommerce-shipping-calculator-in-product/commit/8f9ca5fcb9b3f62cb0e85629109af3a647bf990d

**Comment by Frisoni** [comment]
Ok. Agora está calculando as assinaturas.
