### ISSUE TITLE
Shortcode não funciona

### ISSUE THREAD

**Issue by brendaferreirap** [valdeirs2/woocommerce-shipping-calculator-in-product#6]
Ao adicionar o shortcode ele aparece no topo da página, independente do local que se coloque. Anexei imagens do local onde foi colocado o shortcode e onde aparece a calculadora.

Local do shortcode: https://ibb.co/h6dCiS
Local aparecendo no topo: https://ibb.co/k11tq7

Atualização: troquei o local para aparecer após os meta do produto, ai aparece normalmente e uma mensagem no local do shortcode, ou seja ta colocado no local certo, só não aparece no local definido com o shortcode: https://ibb.co/hb1Mcn

**Comment by Frisoni** [comment]
Também tive o mesmo problema usando o tema Flatsome. Se coloco o shortcode nas configurações do tema fica lá em cima na tela. Só funcionou quando coloco na descrição do produto.

**Comment by valdeirs2** [comment]
@brendaferreirap @Frisoni 

Corrigido no PR https://github.com/valdeirs2/woocommerce-shipping-calculator-in-product/commit/d9fcc52f285ca66347aeee89a16ec9fbec57d7ec

Obrigado pelo report!

**Comment by brendaferreirap** [comment]
Testei aqui e continua só com um problema, o shortcode ta aparecendo com div ja, o que dificulta colocar dentro de outras div, creio que o certo seria pro shortcode aparecer só com o que tem dentro da div, ai daria certo pra colocar em qualquer local.

Aqui a imagem de como ta ficando o código: https://ibb.co/bU7CHn

**Comment by valdeirs2** [comment]
@brendaferreirap, o HTML retornado pelo shortcode necessita estar dentro de um elemento principal, tanto por questões estruturais, quanto por boas práticas.  Não há problemas em uma div estar dentro de outra div, isto é natural em HTML. 

 Acredito que no seu caso seja uma questão de compatibilidade com o seu tema. Parece que vc terá que ajustar o CSS da div com a classe "frete-pag-produto".

**Comment by brendaferreirap** [comment]
Deve ser incombatibilidade com o flatsome mesmo, descobri o que era e tive que ajeitar com css. É o "float:left" do plugin, quando coloco "float: initial" volta tudo ao normal. Obrigada de qualquer forma, vou continuar fazendo testes no plugin.

**Comment by valdeirs2** [comment]
OK, @brendaferreirap. Que bom que resolveu. Certo é que em alguns temas será necessário algum ajuste de CSS como este.

Vou fechar a Issue, obrigado.
