### ISSUE TITLE
Resposta fica em branco algumas vezes

### ISSUE THREAD

**Issue by Achiles-s** [valdeirs2/woocommerce-shipping-calculator-in-product#8]
Em alguns momentos a resposta não aparece. 
Não identifiquei padrões de dispositivos, navegadores,...

**Comment by valdeirs2** [comment]
@Achiles-s, observou com quais tipos de entrega ficou em branco? Caso tenha sido com os Correios (PAC e/ou Sedex), pode ter relação com a indisponibilidade do Webservice deles.

Agora, se haviam outras formas de entrega como Frete Grátis, Frete Fixo e etc, aí eu precisarei de mais detalhes.

**Comment by Achiles-s** [comment]
Então, uso apenas taxa fixa e frete grátis, os padrões do woocommerce. 

No começo achei que estava acontecendo isso mais no mobile, mas também rolou com vários clientes da loja no desktop.

**Comment by valdeirs2** [comment]
@Achiles-s, o problema ainda ocorre? Alguma novidade?
