### ISSUE TITLE
Não funciona com outros tipos de Envio

### ISSUE THREAD

**Issue by rafacrt** [valdeirs2/woocommerce-shipping-calculator-in-product#9]
Só funciona com os correios configurado

Como existem produtos de maior porte em minha loja, os correios não entregam, então uso o serviço de transportadoras como a JadLog, usando sistemas como o do Melhor Envio

O plugin não mostra o cálculo de frete dessas transportadoras, mesmo estando configuradas corretamente como metódo de entrega

Somente correios.

**Comment by valdeirs2** [comment]
Olá, @rafacrt. 

Este plugin não funciona apenas com os Correios. O que ele faz é trazer todas as formas de entrega disponíveis, assim como na página do carrinho.

Tente criar uma forma de entrega com frete fixo, por exemplo. Ele deverá aparecer na página do produto.

**Comment by valdeirs2** [comment]
Issue fechada por falta de resposta.
